spring:
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      #      uri: http://localhost:8401
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/
server:
  port: 8402
management:
  security:
    enabled: false