server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
management:
  security:
    enabled: false
logging:
  file: "logs/boot-admin-sample.log"
spring:
  application:
    name: admin-server

boot:
  admin:
    routes:
      endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

turbine:
  clusters: default
  localtion: service-turbine

endpoint:
  health:
    sensitive: false
    enabled: true
  actuator:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false